routes/web.php
<?php

use App\Models\File;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmpolyeesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
///demo project
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('admin')->as('admin.')->middleware('auth')->group(function() {
    Route::resource('company', CompanyController::class);
    Route::resource('employees', EmpolyeesController::class);
});

Route::get('search', [CompanyController::class, 'search']);





/// image
Route::get('media/get/{file}', function (File $file) {
    if (!Storage::exists($file->getStoragePath())) {
        abort(404, 'Resource Not Found');
    }
    return Storage::response($file->getStoragePath(), $file->name);
})->name('media.get');

app/Models/Company.php
<?php

namespace App\Models;

use App\Models\Employees;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Company extends Model
{
    use HasFactory;
    protected $guarded = [];
    
    public function company()
    {
        return $this->hasMany(Employees::class, 'company_id');
    }
    public function image()
    {
        return $this->belongsTo(File::class, 'image_id');
    }

     public function getImage()
    {
        if ( ! $this->image || ! Storage::exists($this->image->getStoragePath())){
            return asset('');
        }
        
        return $this->image->getPath();
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Models\File;
use App\Models\Company;
use Illuminate\Http\Request;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $company = Company::latest()->paginate(10);
        return view('admin.company.index', compact('company'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|unique:companies|min:4',
            'email' => 'required',
            
        ]);

        if(request()->hasFile('logo')){
            $image = File::UploadFile(request()->file('logo'));
        }

        $company= New Company();
        $company->name = $request->name;
        $company->email = $request->email;
        $company->image_id = $image->id;
        $company->save();

        return redirect()->route('admin.company.index')->with('success', 'Add Successfully');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::find($id);
        return view('admin.company.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validated = $request->validate([
            'name' => 'required|min:4',
            'email' => 'required',
            
        ]);

        if(request()->hasFile('logo')){
            $image = File::UploadFile(request()->file('logo'));
        }

        $company=  Company::find($id);
        $company->name = $request->name;
        $company->email = $request->email;
        $company->image_id = $image->id;
        $company->update();

        return redirect()->route('admin.company.index')->with('success', 'Update Successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $company = Company::find($id);
        $company->delete();

        return redirect()->back()->with('success', 'Delete Successfully');

    }

    public function search(Request $request)
    {
        if($request->ajax()){
            $data = Company::where('name', 'like', '%'.$request->search.'%')->get();

            $output = '';
            if(count($data)>0){

                $output = ' 
            <table class="table">
                <thead>
                    <tr> 
                        <td>#</td>
                        <td>name</td>
                        <td>email</td>
                    </tr>
                </thead>
                <tbody>';
                foreach($data as $row){
                    $output .= '
                    <tr> 
                        <td>' .$row->id. '</td>
                        <td>' .$row->name. '</td>
                        <td>' .$row->email. '<td>
                    </tr>';
                }
                $output.='
                </tbody>
            </table>';

            }else{
                $output.='no result found';
            }

            return $output;
        }
    }
}

resources/views/admin/company/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Add New Company') }}</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <form action="{{ route('admin.company.store')}}" method="POST" enctype="multipart/form-data">              
                        @csrf
                       

                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Company Name</label>
                            <input type="text" class="form-control" name="name" id="slider_describtion" placeholder="Company Name" required>
                        </div>
                        @error('name')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label"> Email</label>
                            <input type="email" class="form-control" name="email" id="slider_describtion" placeholder="Company Email" required>
                        </div>
                        @error('email')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label"> company Logo</label>
                            <input type="File" class="form-control" name="logo"  required>
                        </div>
                        <div class="mb-3 float-right">
                            <button type="submit" class="btn btn-success">Save</button>
                           
                        </div>
                    </form>

                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/company/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Add New Company') }}</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <form action="{{route('admin.company.update',$company->id)}}" method="POST" enctype="multipart/form-data">  

                        @csrf
                       @method('PUT')

                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Company Name</label>
                            <input type="text" class="form-control" name="name" value="{{$company->name}}" id="slider_describtion" placeholder="Company Name" required>
                        </div>
                        @error('name')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label"> Email</label>
                            <input type="email" class="form-control" name="email" value="{{$company->email}}" id="slider_describtion" placeholder="Company Email" required>
                        </div>
                        @error('email')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label"> company Logo</label>
                            <input type="File" class="form-control" name="logo" >
                        </div>
                        <div class="mb-3">
                            <img src="{{$company->getImage()}}" alt="" style="width: 200px; height:150px">
                        </div>
                        <div class="mb-3 float-right">
                            <button type="submit" class="btn btn-success">Update</button>
                           
                        </div>
                    </form>

                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/company/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            @if(session('success'))
                <div class="alert alert-success alert-dismissible" role="alert">
                    <strong>{{ session('success')}}</strong> 
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            @endif
            <div class="card">
                <div class="card-header">{{ __('Company') }}</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <input type="text" name="search" id="search" class="form-control col-6" placeholder="search">
                    <a href="{{route('admin.company.create')}}" class="btn btn-success float-right">Add New Company</a>
                        <br>
                    {{-- <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Company Name</th>
                            <th scope="col">Company Email</th>
                            <th scope="col">Company Logo</th>
                            <th scope="col">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach ($company as $com)
                                <tr>
                                    <th scope="row">{{ $company->firstItem()+$loop->index}}</th>
                                    <td>{{$com->name}}</td>
                                    <td>{{$com->email}}</td>
                                    <td><img src="{{$com->getImage()}}" alt="" style="width: 100px; height:70px;"></td>
                                    <td>
                                        <a href="{{route('admin.company.edit',$com->id)}}" class="btn btn-success">Edit</a>
                                       <form action="{{route('admin.company.destroy',$com)}}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger" >Delete</button>
                                       </form>
                                        
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                      </table>
                      {{ $company->links() }} --}}
                
                
                    </div>
                    <div id="search_list"></div>
            </div>
        </div>
    </div>
</div>
@endsection

<script>

    $(document).ready(function()){
        $('#search').on('keyup', function(){
            var query = $(this).val();
            $.ajax({
                url:"search",
                type: "GET",
                date:{'search':query},
                success:function(data){
                    $('#search_list').html(data);
                }
            });
        });
    }

</script>