routes/web.php
<?php

use App\Models\File;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmpolyeesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
///demo project
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('admin')->as('admin.')->middleware('auth')->group(function() {
    Route::resource('company', CompanyController::class);
    Route::resource('employees', EmpolyeesController::class);
});

Route::get('search', [CompanyController::class, 'search']);





/// image
Route::get('media/get/{file}', function (File $file) {
    if (!Storage::exists($file->getStoragePath())) {
        abort(404, 'Resource Not Found');
    }
    return Storage::response($file->getStoragePath(), $file->name);
})->name('media.get');

app/Models/Employees.php
<?php

namespace App\Models;

use App\Models\Company;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Employees extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function getCompany()
    {
        return $this->belongsTo(Company::class, 'company_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

resources/views/admin/employees/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Add New employees') }}</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                       
                    <form action="{{ route('admin.employees.store')}}" method="POST" enctype="multipart/form-data">              
                        @csrf
                       
                        <div class="mb-3">
                            <select name="company_id" class="form-select" aria-label="Default select example">
                                <option selected>Select Company</option>
                                @foreach ($company as $com)
                                    <option value="{{$com->id}}" >{{$com->name}}</option>    
                                @endforeach
                              </select>
                        </div>
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">First Name</label>
                            <input type="text" class="form-control" name="fname" id="slider_describtion" placeholder="employees First Name" required>
                        </div>
                        @error('fname')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Last Name</label>
                            <input type="text" class="form-control" name="lname" id="slider_describtion" placeholder="employees Last Name" required>
                        </div>
                        @error('lname')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label"> Email</label>
                            <input type="email" class="form-control" name="email" id="slider_describtion" placeholder="employees Email" required>
                        </div>
                        @error('email')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Phone</label>
                            <input type="text" class="form-control" name="phone" id="slider_describtion" placeholder="employees phone" required>
                        </div>
                        @error('phone')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <div class="mb-3 float-right">
                            <button type="submit" class="btn btn-success">Save</button>
                           
                        </div>
                    </form>

                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/employees/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Add New employees') }}</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                       
                    <form action="{{ route('admin.employees.update',$employees->id)}}" method="POST" >              
                        @csrf
                       @method('PUT')
                        <div class="mb-3">
                            <select name="company_id" class="form-select" aria-label="Default select example">
                                <option selected>Select Company</option>
                                @foreach ($company as $com)
                                    <option value="{{$com->id}}" selected>{{$com->name}}</option>    
                                @endforeach
                              </select>
                        </div>
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">First Name</label>
                            <input type="text" class="form-control" name="fname" id="slider_describtion" placeholder="employees First Name" required>
                        </div>
                        @error('fname')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Last Name</label>
                            <input type="text" class="form-control" name="lname" id="slider_describtion" placeholder="employees Last Name" required>
                        </div>
                        @error('lname')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label"> Email</label>
                            <input type="email" class="form-control" name="email" id="slider_describtion" placeholder="employees Email" required>
                        </div>
                        @error('email')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Phone</label>
                            <input type="text" class="form-control" name="phone" id="slider_describtion" placeholder="employees phone" required>
                        </div>
                        @error('phone')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                        <div class="mb-3 float-right">
                            <button type="submit" class="btn btn-success">Update</button>
                           
                        </div>
                    </form>

                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/employees/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            @if(session('success'))
                <div class="alert alert-success alert-dismissible" role="alert">
                    <strong>{{ session('success')}}</strong> 
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            @endif
            <div class="card">
                <div class="card-header">{{ __('employees') }}</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <a href="{{route('admin.employees.create')}}" class="btn btn-success float-right">Add New employees</a>
                        <br>
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">First Name</th>
                            <th scope="col">Last Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Company</th>
                            <th scope="col">employees Phone</th>
                            <th scope="col">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach ($employees as $emp)
                                <tr>
                                    <th>{{ $employees->firstItem()+$loop->index}}</th>
                                    <td>{{$emp->name}}</td>
                                    <td>{{$emp->last_name}}</td>
                                    <td>{{$emp->email}}</td>
                                    <td>{{$emp->company_id }}</td>
                                    <td>{{$emp->phone}}</td>
                                    <td>
                                        <a href="{{route('admin.employees.edit',$emp->id)}}" class="btn btn-success">Edit</a>
                                       <form action="{{route('admin.employees.destroy',$emp)}}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger" >Delete</button>
                                       </form>
                                        
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                      </table>
                      {{ $employees->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection